### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by DarkWake9** [DarkWake9/Project-QG#11]
**_While saving the fig:_**

/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/transforms.py:2657: RuntimeWarning: divide by zero encountered in scalar divide
  x_scale = 1.0 / inw
Traceback (most recent call last):
  File "/scratch/vibhavasu.phy.iith/Project-QG/task2/task2a_dynesty1.py", line 224, in <module>
    plt.savefig(os.getcwd() + '/outputs/fits/' + grbname_wtht_ext + '_fit_logE.png', facecolor='white')
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1023, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/figure.py", line 3343, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2366, in print_figure
    result = print_method(
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2232, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 457, in _print_pil
    FigureCanvasAgg.draw(self)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/figure.py", line 3140, in draw
    mimage._draw_list_compositing_images(
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3064, in draw
    mimage._draw_list_compositing_images(
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/axis.py", line 1376, in draw
    ticks_to_draw = self._update_ticks()
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/axis.py", line 1262, in _update_ticks
    major_locs = self.get_majorticklocs()
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/axis.py", line 1484, in get_majorticklocs
    return self.major.locator()
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/ticker.py", line 2341, in __call__
    return self.tick_values(vmin, vmax)
  File "/home/vibhavasu.phy.iith/anaconda3/envs/vibenv/lib/python3.9/site-packages/matplotlib/ticker.py", line 2366, in tick_values
    log_vmin = math.log(vmin) / math.log(b)
ValueError: math domain error

**Comment by DarkWake9** [comment]
**UPDATE** :

Using try except to plot to skip plotting the error generating GRBs.

Will plot those manually

_**NO SEPARATE LIST FOR ERROR GENERATING GRBs**_
_**WILL FIND THEM MANUALLY**_

**Comment by DarkWake9** [comment]
**UPDATE**:

_Workaround_:

Saved the samplers and manually plotted with another code
